
const GET_SELLER = "GET_SELLER"
const GET_GOODS = "GET_GOODS"
const GET_RATINGS = "GET_RATINGS"
const SHOW_DETAIL = 'SHOW_DETAIL'
const SHOW_FOODDETAIL = 'SHOW_FOODDETAIL'
const SHOW_BUYDETAIL = 'SHOW_BUYDETAIL'
const HIDE_DETAIL = 'HIDE_DETAIL'
const HIDE_FOODDETAIL = 'HIDE_FOODDETAIL'
const HIDE_BUYDETAIL = 'HIDE_BUYDETAIL'


export default {
	GET_SELLER,
	GET_GOODS,
	GET_RATINGS,
	SHOW_DETAIL,
	HIDE_DETAIL,
	HIDE_FOODDETAIL,
	SHOW_FOODDETAIL,
	SHOW_BUYDETAIL,
	HIDE_BUYDETAIL
}